### ISSUE TITLE
Error in minimap alignment

### ISSUE THREAD

**Issue by amootta** [HKU-BAL/SENSV#4]
Hi there, 
I have just downloaded SenSV and am currently trying to use it to analyze some WGS data (approx 4X coverage) of two cell lines. This data was generated using the recently released Nanopore Ultra-Long DNA Sequencing Kit.
 I have produced an appropriate .fastq file to input into the software, and it has managed to complete Step 0 to produce the appropriate gzipped files and index. 
However, I believe the next step is not working for me. In Step 1, no bam or chain files are being generated from my fastq files, depits the step completing and giving a report of the time elapsed. This has led to an error in the following steps (Step 2 and Step 2.1). I am wondering if you could please help me figure out what is going on here, as I am very keen on using the software to confirm some potentially interesting structural variants! 

Thanks very much.

**Comment by ccbruels** [comment]
I am having the same issue! Were you able to resolve it?

If you don't have a resolution, I was thinking about running minimap separately, then commenting out that part of the sensv code to see if that will work.

**Comment by bbvan** [comment]
Hello @amootta and @ccbruels,

We have fixed a bug related to too-long cigar strings caused by ultra-long reads. Yet we are unsure if that resolves the issue as we could not reproduce the missing bam chain/file problem.

You could get the updated version following
https://github.com/HKU-BAL/SENSV#option-2-build-and-anaconda-virtual-environment-step-by-step

In case the bam/chain files produced in Step 1 are still missing, try invoking our modified minimap2 separately by
```sh
$(dirname `which sensv`)/modules/my_minimap2/minimap2 -Y -t `nproc` -z 200 --MD -a <reference> <input fastq file> -5 <output chain filename> > <output sam filename>
```
Kindly let me know if the issue persists, thanks!

**Comment by ccbruels** [comment]
Thanks for the update. My issue turned out to be more hardware/environment specific. 

The initial issue I saw with no bam or chain file being generated was due to an incorrect (for my system?) samtools version that was partially resolved by using the option 2 install. Then other issues related to the university linux being centos not debian, and conda fighting with the system, but we eventually resolved and sensv seems to be running correctly!
